theme: jekyll-theme-leap-day
title: Kang Xue (薛康)
email: kang.xue0622@gmail.com
description: Ph.D.<span style="color:orange">s</span> in Educational Psychology & Electrical Engineering - Research Scientist @ NWEA 
