theme: jekyll-theme-leap-day
title: Kang Xue (薛康)
email: kang.xue0622@gmail.com
description: Ph.D.<sup><span style="color:blue">**2**</span></sup> in Educational Psychology & Electrical Engineering - Research Scientist @ NWEA 
